ALTER TABLE doctors
ALTER COLUMN name TYPE VARCHAR(120);
ALTER TABLE doctors
ALTER COLUMN email TYPE VARCHAR(120);
ALTER TABLE doctors
ALTER COLUMN password TYPE VARCHAR(300);
ALTER TABLE doctors
ALTER COLUMN phone_number TYPE VARCHAR(20);
ALTER TABLE doctors
ALTER COLUMN status TYPE VARCHAR(20);
ALTER TABLE doctors
ALTER COLUMN job_description TYPE TEXT;