ALTER TABLE patients
ALTER COLUMN name TYPE VARCHAR(120);
ALTER TABLE patients
ALTER COLUMN email TYPE VARCHAR(120);
ALTER TABLE patients
ALTER COLUMN password TYPE VARCHAR(300);
ALTER TABLE patients
ALTER COLUMN phone_number TYPE VARCHAR(20);
ALTER TABLE patients
ALTER COLUMN status TYPE VARCHAR(20);
ALTER TABLE patients
ALTER COLUMN birthdate TYPE DATE;
ALTER TABLE patients
ALTER COLUMN allergies TYPE TEXT;
ALTER TABLE patients
ALTER COLUMN gender TYPE VARCHAR(12);
